In [1]:
import numpy as np

##data Types

In [2]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1.shape

(4,)

In [6]:
a2.shape

(2, 3)

In [7]:
a1.dtype,a2.dtype

(dtype('int32'), dtype('int32'))

In [8]:
a1.size


4

In [9]:
a2.size

6

In [10]:
#Create Data Frame from Numpy
import pandas as pd 
df=pd.DataFrame(a2)

In [11]:
df


0  1  2
0  1  2  3
1  4  5  6

In [13]:
ones=np.ones((2,3))

In [14]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
type(ones)

numpy.ndarray

In [16]:
ones.dtype

dtype('float64')

In [17]:
zeros=np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [18]:
range_array=np.arange(0,10,2)

In [19]:
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[5, 8, 7, 6, 1],
       [4, 4, 1, 5, 2],
       [0, 8, 9, 8, 9]])

In [21]:
random=pd.DataFrame(random_array)
random

0  1  2  3  4
0  5  8  7  6  1
1  4  4  1  5  2
2  0  8  9  8  9

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array.size


15

In [28]:
np.random.seed(seed=0)
random_array4=np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
#Viewing

In [30]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a2[0]

array([1, 2, 3])

In [33]:
a1
a1[0]

1

In [34]:
a4=np.random.randint(10,size=(2,3,4,5))

In [35]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [37]:
a4[: ,:,:,:2]

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

In [38]:
a4[: ,:,:3,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0]]]])

In [39]:
a4[: ,:1,:3,:2]

array([[[[6, 7],
         [5, 9],
         [3, 0]]],


       [[[4, 6],
         [4, 4],
         [7, 5]]]])

#Manipulating Arrays

In [42]:
a1 

array([1, 2, 3, 4])

In [43]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
ones=np.ones(4)

In [48]:
ones

array([1., 1., 1., 1.])

In [49]:
a1+ones

array([2., 3., 4., 5.])

In [50]:
a1*ones

array([1., 2., 3., 4.])

In [51]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a1*a1

array([ 1,  4,  9, 16])

In [55]:
a1/ones

array([1., 2., 3., 4.])

In [56]:
a1**2

array([ 1,  4,  9, 16])

In [57]:
 a1%2

array([1, 0, 1, 0], dtype=int32)

In [58]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
massive_array=np.random.random(10000)

In [63]:
massive_array[:100]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839,
       0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093,
       0.11620191, 0.7670237 , 0.41182014, 0.67543908, 0.24979628,
       0.31321833, 0.96541622, 0.58846509, 0.65966841, 0.53320625,
       0.23053302, 0.39486929, 0.61880856, 0.47486752, 0.47013219,
       0.71607453, 0.287991  , 0.38346223, 0.74916984, 0.87845219,
       0.10286336, 0.09237389, 0.35404666, 0.55181626, 0.03362509,
       0.96896177, 0.32099724, 0.22126269, 0.1412639 , 0.09725993,
       0.98404224, 0.26034093, 0.53702252, 0.44792617, 0.09956909,
       0.35231166, 0.46924917, 0.84114013, 0.90464774, 0.03755938,
       0.50831545, 0.16684751, 0.77905102, 0.8649333 , 0.41139672,
       0.13997259, 0.03322239, 0.98257496, 0.37329075, 0.42007537,
       0.05058812, 0.36549611, 0.01662797, 0.23074234, 0.7649117 ,
       0.94412352, 0.74999925, 0.33940382, 0.48954894, 0.33898

In [64]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.87 ms ± 96.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
19.5 µs ± 87.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [65]:
np.std(a1)

1.118033988749895

In [66]:
np.var(a2)

2.9166666666666665

In [67]:
a1.T

array([1, 2, 3, 4])

In [68]:
a1

array([1, 2, 3, 4])